spring:
  application:
    name: Cards-Api-System
  datasource:
    url: jdbc:postgresql://localhost:5432/CardsDB
    username: Userr
    password: 12345
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

security:
  user:
    admin=admin 
    password=password


server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
  ssl:
    enabled: false

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      bank_cards: DEBUG
  file:
    name: logs/bank_cards.log


jwt:
  secret: acb802b56c09b73425d99925464808a9edcbd3026524383c4152b5151eefd8e85abf7033f350fcaf4b189af6a55e4755fbc973adfd72f3abb9a7c8ac75fdf648c88c7b87270993736216dffe954fea841891ecb0a4d721938dea151f9ea71eb6f415f4db757adc62f29881a6ada21be5383ff7e48c04b0751533005f8c7e9bd762e6380f04acc0259afde1cb22df174bc9cf68f7bce56b0edd91247ee62c5a05f835e092a0af37cd0dbd3c414143b87d04ccbf6eb9aaf84f8a7b7b5435cf7c0c8898590301598e846968a1a2506605124836ea33d83f1a10375ada5ca51555ebb3ed65166b1b808f8e665e4a9b6bf60ed725ba8276d369f24090927291907c46
  expiration: 86400000
  refreshExpiration: 86400000
  prefix: Bearer
  header: Authorization
  tokenPrefix: Bearer
  userClaim: role


swagger:
  servers: "http://localhost:8080"


springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/api-docs

jasypt:
  encryptor:
    password: ymMfhyWVONVZSsrVTbVAQdnSoCjQObleBrrqJEQCDIzYvGwSVm
